version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    ports:
      - '8000:8000'
    networks:
      - backend
    tty: true
    depends_on:
      - db
    volumes:
      - $PWD:/home
  db:
    image: postgres:14.1-alpine
    container_name: db
    hostname: db
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'